backend/controllers/InvoiceController.php
<?php

namespace backend\controllers;
use Yii;

use common\models\OrderLines;
use common\models\OrderPayments;
use common\models\Orders;
use common\models\StockOnHand;
use common\models\OrdersSearch;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\db\Query;


class InvoiceController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionNewinvoice(){
        $max = Orders::find()->max('id');
        return $this->render('newinvoice',['invoiceNum'=>$max]);
    }

    public function actionSaveinvoice(){
       //print_r($_POST);die();

        $order = new Orders();
        $transaction = yii::$app->db->beginTransaction();

        try{
            $order->customer_id = $_POST['hdCustomerId'];
            $order->sponsor_id = $_POST['hdSponsorId'];
            $order->grand_total = $_POST['hdGrandTotal'];
            $order->sub_total = $_POST['hdSubTotal'];
            $order->mini_subsidy = $_POST['hdMiniSubsidyDiscount'];
            $order->mini_subsidy_perc = $_POST['hdSubsidyPerc'];
            $order->discount = $_POST['hdTotalDiscount'];
            $order->amount_due = $_POST['hdAmountDue'];
            $order->mini_accumulated_sales=$_POST['hdAccumulatedSales'];
            $order->created_by = \Yii::$app->user->id;
            $order->is_invoice = 1;
            $order->is_paid=0;
            $order->terms=$_POST['hdTerms'];
            $order->prev_balance=$_POST['hdBalance'];
            $order->remaining_balance = $_POST['hdAmountDue'];
            $order->due_date = date('Y-m-d',strtotime("+". $_POST['hdTerms'] . " days" ));

            if($order->save()){
                $lineCount = $_POST['hdLineCount'];

                for($i=1;$i<=$lineCount;$i++) {
                    if(isset ($_POST['qty' . $i])) {
                        $line = new OrderLines();
                        $line->order_id = $order->id;
                        $line->qty = $_POST['qty' . $i];
                        $line->product_id =  $_POST['hd_pid' . $i];
                        $line->srp =  $_POST['hd_srp' . $i];
                        $line->total =  $_POST['hd_subtotal' . $i];
                        $line->discount =  $_POST['hd_discount' . $i];
                        $line->amount =  $_POST['hd_total' . $i];

                        if($line->save()){
                            $inventory = StockOnHand::findOne(['product_id'=>$line->product_id]);
                            $old = $inventory->quantity;
                            $new  = floatval($old) - floatval($line->qty);

                            $inventory->quantity = $new;
                            $inventory->save();
                        }
                    }

                }
                $transaction->commit();

                $newOrder =  Orders::findOne(['id'=>$order->id]);
                return $this->redirect(['/invoice/printreceipt', 'id' => $order->id]);
                //return $this->render('receipt',['order'=>$newOrder]);
            }

        }catch (Exception $ex){
            $transaction->rollBack();
        }

    }

    public function actionPrintreceipt($id){
        $newOrder =  Orders::findOne(['id'=>$id]);
        return $this->render('receipt',['order'=>$newOrder]);
    }

    public function actionInvoices(){
        return $this->render('invoices');
    }

    public function actionInvoicelist(){
        $query = new Query;

        $date_from = $_POST['datefrom'];
        $date_to = $_POST['dateto'];

        $query->select('*')
            ->from('vw_sales_invoices')
            ->where(' date(created) between :start_date AND :end_date AND is_invoice=1',[':start_date' => $date_from,':end_date'=>$date_to])
            ->orderBy(['id'=>SORT_ASC]);

        $command = $query->createCommand();
        $data = $command->queryAll();

        echo json_encode($data);

    }

    public function actionPayorder(){
       // print_r($_POST);die();
        $order = Orders::findOne(['id'=> $_POST['hdOrderId']]);
        $transaction = yii::$app->db->beginTransaction();

        try{
            $date_now = date("d F Y");
            $date_now = strtotime($date_now);
            $date_now = date("Y/m/d H:i:s", $date_now);

            $order->last_payment_date =$date_now;
            $balance = floatval($order->remaining_balance) - floatval($_POST['txtAmount']);
            $order->remaining_balance= $balance;
            if($balance <1 ){
                $order->is_paid=1;
                $order->remaining_balance= 0;
            }
            $order->save();

            $orderPayment = new OrderPayments();
            $orderPayment->order_id = $order->id;
            $orderPayment->total_amount = $_POST['hdGrandTotal'];
            $orderPayment->amount_paid = $_POST['txtAmount'];
            $orderPayment->payment_type = $_POST['payment_type'];
            $orderPayment->is_invoice = 1;
            if($_POST['payment_type'] == 'cheque') {
                $orderPayment->bank_name = $_POST['txtBankName'];
                $orderPayment->bank_number = $_POST['txtBankNumber'];
                $orderPayment->cheque_number = $_POST['txtChequeNumber'];
            }

            $orderPayment->save();
            $transaction->commit();

            //$newOrder =  Orders::findOne(['id'=>$order->id]);
            return $this->redirect(['/invoice/printreceipt', 'id' => $order->id]);

        }catch (Exception $ex){
            $transaction->rollBack();
        }
    }



}

backend/views/invoice/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>invoice/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

backend/views/invoice/invoices.php
<?php
use yii\jui\DatePicker;

$this->registerJsFile('@web/js/jquery.dataTables.min.js',['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/dataTables.bootstrap.min.js',['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/orders.js',['depends' => [\yii\web\JqueryAsset::className()]]);

?>

    <div class="row">

        <div class="col-md 12">
            <h2>Sales Invoices</h2>

        </div>
        <hr />
    </div>

    <div class="row">
        <h4>Select Dates</h4>
        <div class="row">
            <div class="col-md-3" id="get_commission_type">
                <p><b>From:</b></p>
                <?=
                DatePicker::widget(['name' => 'from','options' => ['class' => 'form-control','id'=>'from'],'dateFormat' => 'yyyy-MM-dd']);
                ?>
            </div>


            <div class="col-md-3" id="get_commission_period">
                <div id="get_commission_period_options">
                    <p><b>To:</b><p>
                </div>
                <div id="select_commission_period" >
                    <?=
                    DatePicker::widget(['name' => 'to','options' => ['class' => 'form-control','id'=>'to'],'dateFormat' => 'yyyy-MM-dd']);
                    ?>
                </div>
            </div>

            <div class="col-md-3" id="get_commissions" >
                <a id="btn_generate" style="margin-top: 30px"  href="javascript:void(0);" class="btn btn-success"><span class='glyphicon glyphicon-search' aria-hidden='true'></span>&nbsp; View Report</a>

            </div>
        </div>

        <hr />
    </div>

    <div class="row">
        <div class="col-md-12">

            <table id="example" class="display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Invoice #</th>
                    <th>Customer</th>
                    <th>Referrer</th>
                    <th>Date</th>
                    <th>Due Date</th>
                    <th>Last Date Paid</th>
                    <th>Remaining Balance</th>
                </tr>
                </thead>

                <tbody>

                </tbody>
            </table>

        </div>
    </div>

<?php
$scrpt = <<<EOD
var tbl_history;
$(document).ready(function () {
    $('#example').DataTable();

    NewOrders.init();

    $('#btn_generate').on('click',function(){


		var date_from = $('#from').val();
		var date_to = $('#to').val();
		var data = {datefrom:date_from,dateto:date_to};


		$.ajax({
		  url: '/invoice/invoicelist',
		  type:"POST",
		  data: data,
		  dataType:'json',
		  success: function(data){
            loadTable(data);
		  }
		});
	});

    tbl_history = $("#example").DataTable();
});

function loadTable(data) {

    tbl_history.destroy();
    $('#example tbody').html('');

    $('#example tbody').html('');
    var html = "";
    var total = 0;
    $.each(data, function (index, object) {
        html += "<tr>";
        html += "<td><a href='/invoice/printreceipt?id="+object.id+"'>"+pad(object.id,9)+"</a></td>";
        html += "<td>"+object.customer_name+"</td>";
        html += "<td>"+object.sponsor_name+"</td>";
        html += "<td>"+object.created+"</td>";
        html += "<td>"+object.due_date+"</td>";
        html += "<td>"+object.last_payment_date+"</td>";
        html += "<td>"+object.remaining_balance+"</td>";
        html += "</tr>";

    });

    $('#example tbody').append(html);
    tbl_history = $('#example').DataTable({pageLength:25});
}

function pad(num, size) {
    var s = num+"";
    while (s.length < size) s = "0" + s;
    return s;
}
EOD;

$this->registerJs($scrpt, $this::POS_END, 'init-corejs');

?>